### PR TITLE
Add password update form/logic

### PR DESCRIPTION
**Pull request by RDelorier**
Add password update form to profile settings page.
@austintoddj I don't know if I did the notifications (errors,success) the right way for the project but the password update is working so you can update the messages and make them how you prefer.

### CODE REVIEW

**Comment by RDelorier** [comment]
adding tests now, 1 sec

**Comment by austintoddj** [comment]
Thanks for doing this @RDelorier. As soon as you're ready and @fergthh, I'll merge this in.

**Comment by RDelorier** [comment]
Okaythis is good to go now, whenever your ready @fergthh

**Comment by RDelorier** [comment]
No problem @austintoddj if you want to go ahead and merge fergs current pr then I can just open a new one to your repo instead

**Comment by austintoddj** [comment]
Will do @RDelorier , in progress..

**Comment by RDelorier** [comment]
Moving to main repo

**Comment by fergthh** [comment]
Merged! Great works @RDelorier! ;) Thanks!

**Comment by RDelorier** [comment]
😄 Just a minute too late lol, I thought you might have been off for the night sorry about that.

**Comment by fergthh** [comment]
Yeah, I late to answer. No problem, I was having dinner with my family so I
saw it late LOL

**Comment by austintoddj** [comment]
Since either one of you has a knack for doing this, I wonder if you'd want to try tweaking this just a tad to make the password reset form sit on it's own tab in the profile section. The picture attached is a quick mockup of it. Basically all the logic is there, just want to make the password reset form sit by itself under it's own tab, separating the normal profile info with the account security. @RDelorier @fergthh 
screen shot 2016-07-10 at 9 10 36 pm

**Comment by RDelorier** [comment]
Sure I don't mind, the forms in a partial so should be able to copy it into a tab

**Pull request closed without merging**
